(define (problem merry1)
    (:domain merry)
    (:objects
        a b c d e f g h i - room
        ga pb yc bc gd rd be ge bf b2f gh rh yi bi - scolor
    )

    (:init
        (iscolor a ga)
        (iscolor b pb)
        (iscolor c yc)
        (iscolor c bc)
        (iscolor d gd)
        (iscolor d rd)
        (iscolor e be)
        (iscolor e ge)
        (iscolor f bf)
        (iscolor f b2f)
        (iscolor h gh)
        (iscolor h rh)
        (iscolor i yi)
        (iscolor i bi)

        (from a b yc)
        (from a b yi)
        (from a c rd)
        (from a c rh)
        (from c a rh)
        (from c a rd)
        (from b d yc)
        (from b d yi)
        (from c e ga)
        (from c e gd)
        (from c e ge)
        (from c e gh)
        (from e c ga)
        (from e c gd)
        (from e c ge)
        (from e c gh)
        (from d f ga)
        (from d f gd)
        (from d f ge)
        (from d f gh)
        (from f d ga)
        (from f d gd)
        (from f d ge)
        (from f d gh)
        (from e f bc)
        (from e f be)
        (from e f bf)
        (from e f b2f)
        (from e f bi)
        (from f e bc)
        (from f e be)
        (from f e bf)
        (from f e b2f)
        (from f e bi)
        (from f i bc)
        (from f i be)
        (from f i bf)
        (from f i b2f)
        (from f i bi)
        (from i f bc)
        (from i f be)
        (from i f bf)
        (from i f b2f)
        (from i f bi)
        (from h i bc)
        (from h i be)
        (from h i bf)
        (from h i b2f)
        (from h i bi)
        (from i h bc)
        (from i h be)
        (from i h bf)
        (from i h b2f)
        (from i h bi)
        (from h e rd)
        (from e h rd)
        (from h e rh)
        (from e h rh)
        (from f g pb)

        (position f)
    )

    (:goal
        (and
            (position a)
        )
    )

)